### ISSUE TITLE
Automatické nasazování aktualizací - změna DNS na GitHub Pages

### ISSUE THREAD

**Issue by MikkCZ** [l10ncz/l10ncz#9]
@pmkovar měli bychom asi trochu oživit web a trochu by pomohlo automatické nasazování, když uděláme nějakou změnu. Nejjednodušší řešení by bylo použít GitHub pages.

Pro GH pages by bylo potřeba nastavit DNS záznamy podle https://help.github.com/articles/setting-up-an-apex-domain-and-www-subdomain/ (subdoména je l10ncz.github.io) a https://help.github.com/articles/troubleshooting-custom-domains/#https-errors.

Určitě je při tom potřeba také zrušit wildcard (* CNAME), který teď směruje na www.l10n.cz. Jediné subdomény, o kterých vím a mají zůstat fungovat, jsou lists.l10n.cz a wiki.l10n.cz. Ty ale mají své vlastní A záznamy.

Pokud si pamatuji, přístup k DNS má @vojtechtrefny, že?

**Comment by vojtechtrefny** [comment]
Právě že přístup k DNS už bohužel nemám. Měl jsem, ale všechno jsem to předal, když jsem odešel z Ubuntu. Budu muset zase začít kopat do stávajícího předsedy, ať s tím něco udělá.

**Comment by MikkCZ** [comment]
OK, budu držet palce. ;)

**Comment by MikkCZ** [comment]
Trochu jsem prozatím automatizoval aktualizace z GitHubu. Možný postup je následující:
- vyrobit a pushnout tag, ze kterého se má nasadit (skript [`release.sh`](https://github.com/l10ncz/l10ncz/blob/master/release.sh))
- počkat na doběhnutí Travis CI (tím se vytvoří platný release a nahraje `.tar.gz` výsledného statického webu)
- na serveru pustit nahraný skript [`deploy-latest-github-release-to-www.sh.zip`](https://github.com/l10ncz/l10ncz/files/1820369/deploy-latest-github-release-to-www.sh.zip), který stáhne poslední release, uloží ho a také rozbalí, kam patří

**Comment by pmkovar** [comment]
Jako workaround to zní docela chytře, díky!
